language: android
# - tools
# - platform-tools
sudo: false

before_install:
  - nvm install 6
  - node --version

  - wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin
  - chmod +x android-ndk-r10e-linux-x86_64.bin
  - ./android-ndk-r10e-linux-x86_64.bin | grep ndk-build.cmd
  - export ANDROID_NDK=`pwd`/android-ndk-r10e
  - echo $ANDROID_NDK
install: 
  - npm install
android:
  components:
  - build-tools-23.0.1
  - build-tools-23.0.2
  - android-23 
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-16
cache:
  directories:
  - node_modules
script:
  - cd android 
  - ./gradlew assembleRelease | grep fail
  - cd ./app/build/outputs/apk
  - ls
  - curl -F 'file=@app-internal-release-5.3.1.apk' -F 'uKey=7d42c69844b88157360fe2dc141fdf1a' -F '_api_key=be1290e71bb2fab7a9547cda2ee37d7b' 'https://www.pgyer.com/apiv1/app/upload'
