language: android
sudo: require
env:
  global:
    - ndkVersion=r10e
before_install: #1.1
  - nvm install 6
  - node --version
install: #1.2
  - npm install
  - rm -rf node_modules/react-native-svg/android/build
  # android-ndk
  - wget http://dl.google.com/android/ndk/android-ndk-r10e-darwin-x86_64.bin
  - sudo chmod +x android-ndk-r10e-darwin-x86_64.bin
  - ls -l
  - ./android-ndk-r10e-darwin-x86_64.bin
  - export ANDROID_NDK=`pwd`/android-ndk-r10e
android: #1.3
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
cache:
  directories:
  - node_modules
script: 
#  - npm run ci #2
  - cd android
  - ./gradlew assembleRelease #3
  - cd ./app/build/outputs/apk
  - ls
  
  - curl -F 'file=@app-internal-release-5.3.1.apk' -F 'uKey=7d42c69844b88157360fe2dc141fdf1a' -F '_api_key=be1290e71bb2fab7a9547cda2ee37d7b' 'https://www.pgyer.com/apiv1/app/upload'
